### ISSUE TITLE
Can get different scores depending on direction

### ISSUE THREAD

**Issue by slowe** [rosswintle/static-word-game#13]
If player 1 has, say, played the word "TOXIC" horizontally then player 2 adds an "O" above the "X" they get different scores depending on the direction. If they have played the "O" horizontally (e.g. by accident) they get a score of 10 but they get 9 if played vertically. This issue would presumably go if there was a dictionary that limited words. Or perhaps just a simple check for one letter words that don't exist?

**Comment by rosswintle** [comment]
Thanks for the report.

According to [the official rules of Scrabble](https://playscrabble.com/news-blog/scrabble-rules-official-scrabble-web-games-rules-play-scrabble), a word must be two letters long.

So I think I'll disable the option to play the word until the played word has two letters.

Does that fix this?
