### ISSUE TITLE
Only the main word played is scored

### ISSUE THREAD

**Issue by rosswintle** [rosswintle/static-word-game#2]
Multiple new words can be created in a single move. Currently only the main word played is scored. All words added should be scored.

**Comment by jessamynwest** [comment]
Related, if you build out from another letter it doesn't see the letters already on the board as part of the word. Like, I played ROOM here but it says I played OOM.

<img width="479" alt="Screenshot 2024-04-14 at 18 43 58" src="https://github.com/rosswintle/static-word-game/assets/698448/d9b68be6-d8c3-45a7-9dc9-21a99e9dd765">

**Comment by rosswintle** [comment]
Ah dang. Good spot. Game logic is harder than I thought!

I have a fix for my initial thing, but not for your thing. Coming soon!

**Comment by rosswintle** [comment]
This should work now.
