### ISSUE TITLE
font smoothing makes some letters "bigger" than others

### ISSUE THREAD

**Issue by jessamynwest** [rosswintle/static-word-game#7]
O is bigger than all the other capital letters in this screenshot.

<img width="778" alt="Screenshot 2024-04-14 at 18 53 57" src="https://github.com/rosswintle/static-word-game/assets/698448/dc30e1f0-305f-4b93-bae6-3cbf66073b04">

**Comment by rosswintle** [comment]
Thanks Jessamyn. I'm not familiar with how to fix this. [CSS font-smooth](https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth) seems to be a non-standard property.

Can you suggest a fix please?

Thanks

**Comment by jessamynwest** [comment]
Gosh I wish I did, it was just a thing I noticed not a thing I have any idea how to approach. Different font that smooths differently maybe?

**Comment by rosswintle** [comment]
OK. I'll close this for now. I'm not sure what to do. Thanks for reporting though!

I'll probably re-style the thing in a few weeks if it's still being used.
